CREATE TABLE MODULES
(
	MODULE_CODE VARCHAR(15) NOT NULL,
	MODULE_NAME VARCHAR(255) NOT NULL,
	MODULE_CREDITS INT NOT NULL,
	MODULE_HOURS INT NOT NULL,
	CONSTRAINT PK_MODULES PRIMARY KEY(MODULE_CODE)
)

CREATE TABLE USERS 
(
	USER_ID INT NOT NULL IDENTITY(1,1),
	USER_NAME VARCHAR(25) NOT NULL,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	CONSTRAINT PK_USERS PRIMARY KEY(USER_ID)
)

CREATE TABLE SEMESTERS
(
	SEMESTER_ID INT NOT NULL IDENTITY(1,1),
	SEMESTER_WEEKS INT NOT NULL,
	SEMESTER_START_DATE DATE NOT NULL,
	CONSTRAINT PK_SEMESTERS PRIMARY KEY(SEMESTER_ID)
)

CREATE TABLE SEMESTER_MODULE_DETAILS
(
	MODULE_CODE VARCHAR(15) NOT NULL,
	SEMESTER_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	SELF_STUDY_HOURS INT NOT NULL,
	REMAINING_HOURS INT NOT NULL,
	CONSTRAINT PK_SMD PRIMARY KEY(MODULE_CODE,SEMESTER_ID,USER_ID),
	CONSTRAINT FK_MODULES_SMD FOREIGN KEY(MODULE_CODE) REFERENCES MODULES(MODULE_CODE),
	CONSTRAINT FK_SEMESTERS_SMD FOREIGN KEY(SEMESTER_ID) REFERENCES SEMESTERS(SEMESTER_ID),
	CONSTRAINT FK_USERS_SMD FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
)

INSERT INTO MODULES VALUES
('BUIS5111','Business Information Systems',15 ,3),
('IQTT5111','Introduction to Quantitative Thinking and Techniques',20 ,4),
('PROG5121','Programming 1A',20,4),
('PRLD5121','Programming Logic and Design',25 ,5),
('OPSY5121','Operating Systems',10 ,2),
('ITPP5112','IT Professional Practice',20 ,2),
('PROG6112','Programming 1B',25 ,4),
('WEDE5020','Web Development (Introduction)',20 ,3),
('DATA6211','Database Introduction',15,4),
('PROG6221','Programming 2A',25 ,3),
('SAND6221','Systems Analysis and Design',15 ,5),
('CIED5111','Civil Engineering Design 1A',12 ,5),
('ECHE5111','Engineering Chemistry 1A',14 ,2),
('EMTH5111','Engineering Mathematics 1A',18 ,3),
('EPHY5111','Engineering Physics 1A',14 ,3),
('SAPR5111','Society and Practice 1A',12 ,2),
('ESCIE5112','Earth Sciences 1B',12 ,3),
('STRU7312','Structural Engineering 3B',15 ,5),
('BMNG5121','Business Management 1A',15 ,4),
('ENFL6111','English for Law',15 ,5),
('ACBP5121','Accounting 1A',15 ,2),
('LACO6221','Law of Contract',15 ,3),
('BSTA6212','Business statistics',15 ,5),
('LEIN5112','Legal Interpretation',15 ,3),
('ENED6122','English for Education',20 ,3),
('IPTL6111 ','IP Teaching and Learning',10 ,4),
('TIMA5111','TIP* Mathematics 1A',25 ,5),
('CDLT6211','Child Development',30 ,4)

SELECT * FROM MODULES